version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  api: &api
    build: api
    tty: true
    stdin_open: true
    command: bash start.sh
    volumes:
      - ./api:/api
    ports:
      - 3030:3030
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      SECRET_KEY_BASE: e8ff232f3d80e047f25c8d9c343582c090a9dda988cd315eed89ea634ac8a4043949cb5f6fe5cc18ddcf53f62d146a9dab723e93cc7fa217abfe9bb236756429
      SMTP_HOST: mailcatcher
      SMTP_PORT: "1025"

  client: &client
    build: client
    command: bash start-client.sh
    tty: true
    stdin_open: true
    volumes:
      - ./client:/var/www/html
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      REACT_APP_API_URL: http://localhost:3030
  
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
