// Dicionário básico PT->EN para países mais comuns
export const countryPtToEn = {
  'alemanha': 'germany',
  'brasil': 'brazil',
  'frança': 'france',
  'espanha': 'spain',
  'italia': 'italy',
  'estados unidos': 'united states',
  'reino unido': 'united kingdom',
  'portugal': 'portugal',
  'argentina': 'argentina',
  'china': 'china',
  'japão': 'japan',
  'canadá': 'canada',
  'mexico': 'mexico',
  'russia': 'russia',
  'india': 'india',
  'australia': 'australia',
  'chile': 'chile',
  'colombia': 'colombia',
  'paraguai': 'paraguay',
  'uruguai': 'uruguay',
  'peru': 'peru',
  'bolivia': 'bolivia',
  'venezuela': 'venezuela',
  'suiça': 'switzerland',
  'suécia': 'sweden',
  'noruega': 'norway',
  'dinamarca': 'denmark',
  'finlândia': 'finland',
  'polonia': 'poland',
  'grecia': 'greece',
  'turquia': 'turkey',
  'egito': 'egypt',
  'africa do sul': 'south africa',
  'coreia do sul': 'south korea',
  'nova zelandia': 'new zealand',
  'irlanda': 'ireland',
  'islandia': 'iceland',
  'marrocos': 'morocco',
  'tunisia': 'tunisia',
  'argelia': 'algeria',
  'siria': 'syria',
  'iraque': 'iraq',
  'iran': 'iran',
  'arabia saudita': 'saudi arabia',
  'emirados arabes unidos': 'united arab emirates',
  'israel': 'israel',
  // Adicione mais conforme necessário
};
