# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.2'

gem 'active_model_serializers', '~> 0.10.0'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'devise'
gem 'devise_token_auth'
gem 'i18n'
gem 'devise-two-factor'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'rails', '~> 7.0.4', '>= 7.0.4.3'
gem 'bcrypt'
gem 'active_model_otp'
gem 'devise-encryptable'
gem "rqrcode", "~> 2.0"
gem 'chunky_png', '~> 1.3', '>= 1.3.5'
gem 'faraday', '~> 2.7'

group :development, :test do
 gem 'rails-controller-testing'
  gem 'simplecov', require: false
  gem 'database_cleaner'
  gem 'thin'
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'listen', '~> 3.3'
  gem 'pry'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 4.0'
  gem 'rubocop-rails'
  gem 'rubocop-rspec',        require: false
  gem 'rubocop-performance',  require: false
  gem 'webmock', '~> 3.18'
  gem 'shoulda-matchers', require: false
  gem 'spring'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
